apiVersion: v1
kind: Service
metadata:
  name: my-dear-watson-api-service
  namespace: ml-pipelines
spec:
  type: ClusterIP
  selector:
    app: my-dear-watson-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000